use Example;

CREATE TABLE ADDRESS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
	STREET VARCHAR(128),
	HOUSENUMBER VARCHAR(128),
	ZIP VARCHAR(128),
	CITY VARCHAR(128)
);

ALTER TABLE PERSON 
	ADD ID_ADDRESS INT NULL;

ALTER TABLE PERSON 
	ADD FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS(ID);